import mongoose, { Document, Schema } from 'mongoose';

// Lesson content types
export interface ILessonContent {
  videoUrl?: string; // YouTube URL
  transcript?: { text: string; start: number; duration: number }[]; // YouTube transcript
  articleContent?: any; // TipTap JSON content
  articleHtml?: string; // Rendered HTML from TipTap
}

export interface ILesson {
  _id?: mongoose.Types.ObjectId;
  title: string;
  description?: string;
  contentType: 'video' | 'article' | 'video-article'; // Can have both
  content: ILessonContent;
  duration: number; // Estimated duration in minutes
  order: number; // Position within module
  hasQuiz: boolean;
  quizData?: any; // Quiz questions JSON (to be generated by AI)
  createdAt?: Date;
  updatedAt?: Date;
}

export interface IModule {
  _id?: mongoose.Types.ObjectId;
  title: string;
  description?: string;
  lessons: ILesson[];
  order: number; // Position within course
  createdAt?: Date;
  updatedAt?: Date;
}

export interface ICourse extends Document {
  organizationId: mongoose.Types.ObjectId;
  title: string;
  description?: string;
  category: string; // Dynamic categories per organization
  thumbnailUrl?: string;
  status: 'draft' | 'published' | 'archived';
  modules: IModule[]; // Embedded modules
  estimatedDuration: number; // in minutes (auto-calculated)
  createdBy: mongoose.Types.ObjectId; // User who created
  createdAt: Date;
  updatedAt: Date;
}

// Lesson Schema (embedded)
const LessonSchema = new Schema({
  title: { type: String, required: true },
  description: { type: String },
  contentType: {
    type: String,
    enum: ['video', 'article', 'video-article'],
    required: true
  },
  content: {
    videoUrl: { type: String },
    transcript: [{
      text: { type: String },
      start: { type: Number },
      duration: { type: Number }
    }],
    articleContent: { type: Schema.Types.Mixed }, // TipTap JSON
    articleHtml: { type: String }
  },
  duration: { type: Number, default: 0 },
  order: { type: Number, required: true },
  hasQuiz: { type: Boolean, default: false },
  quizData: { type: Schema.Types.Mixed }
}, {
  timestamps: true
});

// Module Schema (embedded)
const ModuleSchema = new Schema({
  title: { type: String, required: true },
  description: { type: String },
  lessons: [LessonSchema],
  order: { type: Number, required: true }
}, {
  timestamps: true
});

const CourseSchema = new Schema<ICourse>({
  organizationId: { type: Schema.Types.ObjectId, ref: 'Organization', required: true, index: true },
  title: { type: String, required: true },
  description: { type: String },
  category: {
    type: String,
    default: 'other'
  },
  thumbnailUrl: { type: String },
  status: { type: String, enum: ['draft', 'published', 'archived'], default: 'draft' },
  modules: [ModuleSchema], // Embedded modules with lessons
  estimatedDuration: { type: Number, default: 0 }, // Auto-calculated from modules/lessons
  createdBy: { type: Schema.Types.ObjectId, ref: 'User', required: true },
}, {
  timestamps: true,
});

// Indexes
CourseSchema.index({ organizationId: 1, status: 1 });
CourseSchema.index({ organizationId: 1, category: 1 });

// Clear cache
if (mongoose.models.Course) {
  delete mongoose.models.Course;
}

export default mongoose.model<ICourse>('Course', CourseSchema);
